### ISSUE TITLE
White CSS Border around Page

### ISSUE THREAD

**Issue by bwiggs** [NicChappell/unit-conversion#2]
If you don't want that white border on the app, add the following css to disable the margin no html and body.

```css
html, body { margin: 0; padding: 0; }
```
